2018-03-22T16:33:32.028Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: The current identity, with the name 'KPT@outbound-logistics' and the identifier 'e651876c6cd882341c67d51e7ebcbb4b5ea19751fd81563bd066293fa499dffc', must be activated (ACTIVATION_REQUIRED))
    at /home/chris/workspace/logistics-chain/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-22T16:33:32.029Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'KPT@outbound-logistics' and the identifier 'e651876c6cd882341c67d51e7ebcbb4b5ea19751fd81563bd066293fa499dffc', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'KPT@outbound-logistics' and the identifier 'e651876c6cd882341c67d51e7ebcbb4b5ea19751fd81563bd066293fa499dffc', must be activated (ACTIVATION_REQUIRED))\n    at channel.queryByChaincode.then.catch (/home/chris/workspace/logistics-chain/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-03-22T16:33:32.029Z ERROR   HLFConnection           :ping()                   {"message":"Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'KPT@outbound-logistics' and the identifier 'e651876c6cd882341c67d51e7ebcbb4b5ea19751fd81563bd066293fa499dffc', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'KPT@outbound-logistics' and the identifier 'e651876c6cd882341c67d51e7ebcbb4b5ea19751fd81563bd066293fa499dffc', must be activated (ACTIVATION_REQUIRED))\n    at _checkRuntimeVersions.then.catch (/home/chris/workspace/logistics-chain/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)\n    at <anonymous>"}$
2018-03-22T16:33:37.417Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Participant 'outbound.logistics.participant.PortCompany#KPT' does not have 'CREATE' access to resource 'org.hyperledger.composer.system.Identity#874354c81d9498254944201be15fd84a809318372891042b088d2e409430d270')
    at /home/chris/workspace/logistics-chain/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-22T16:33:37.418Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Participant 'outbound.logistics.participant.PortCompany#KPT' does not have 'CREATE' access to resource 'org.hyperledger.composer.system.Identity#874354c81d9498254944201be15fd84a809318372891042b088d2e409430d270')\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Participant 'outbound.logistics.participant.PortCompany#KPT' does not have 'CREATE' access to resource 'org.hyperledger.composer.system.Identity#874354c81d9498254944201be15fd84a809318372891042b088d2e409430d270')\n\n    at _initializeChannel.then.then.then.then.catch (/home/chris/workspace/logistics-chain/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
